### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AhmerAfzal1** [KnIfER/PolymPic#1]
First of all thanks for this great PdfViewer library based on Pdfium. I request you please become a maintainer for [barteksc PdfViewer](https://github.com/barteksc/AndroidPdfViewer) so everyone benefit from you.

**Comment by KnIfER** [comment]
That project is too complex to modify, it has so many source files but I've done better using just one source file. I knew about this project years ago, but I am still frightened by its weird way of invoking.

so. . I'm afraid I don't have the time and ability to improve barteksc/PdfViewer, sorry.

**Comment by AhmerAfzal1** [comment]
First of all I thank you for answering me. I respect your answer, but I think it would be great if you could take a little time out once a month for [Barteksc PdfViewer](https://github.com/barteksc/AndroidPdfViewer). If you don't, here's another suggestion for you, if you forked a [Barteksc library](https://github.com/barteksc/AndroidPdfViewer) and move it forward, a lot of people will benefit from you. And you have so much potential for it.

**Comment by KnIfER** [comment]
What do you want me to do for Barteksc's AndroidPdfViewer specifically?

The latest alpha version is released in the release area, please try it. I think most developers just want a pdf viewer that they can invoke to view some docs.

**Comment by AhmerAfzal1** [comment]
Ok and thanks @KnIfER
