### ISSUE TITLE
屏幕坐标转换成pdf page 坐标问题

### ISSUE THREAD

**Issue by hehonghui** [KnIfER/PolymPic#4]
Hi, @KnIfER 无意中看到了你的文章 [制作安卓PDF阅读器：三、实现文本选择](https://www.jianshu.com/p/6a2ccadc668d), 觉得写的很不错，不过有一个问题没太明白, 想请教一下。

```
需要将屏幕坐标转换为页面坐标，然后再次在native层转换为所谓的user space、page space。别问我那是啥我也不知道。不过在论坛提问后，有人替我指出了相关文档所在，有时间去看看！

"User space" is defined in section 8.3.2.3 of the PDF 32000-1:2008 specification.

屏幕坐标：[event.getX(), event.getY()]
页面坐标：先前提过将整本PDF当作一张超级大图，subsampling-scale-imageview 有一系列的 viewToSource 坐标转换方法。屏幕转换得到 source 坐标后，减去点击页面的左上角坐标，就是页面坐标。

原始页面坐标需用 FPDF_DeviceToPage 再次转换，才能传给FPDFLink_GetLinkAtPoint，获取坐标处的链接指针。
```

上述描述中的坐标转换问题在没有上下文的情况下不好理解，能否分享一下实现思路？ 感谢, :)

**Comment by KnIfER** [comment]
忘记了……

代码里有的吧，具体看就明白了

**Comment by KnIfER** [comment]
先找到jni层调用的方法，mainJNILib.cpp中找

比如你可以参考一下  nativeGetLinkAtCoord，在屏幕落点处检测是否存在超链接对象。

https://github.com/KnIfER/PolymPic/blob/f0040b0a90ba2c5a5236bb47a3fc3355fe979628/LibPdfium/src/main/jni/src/mainJNILib.cpp#L1007

就是这般传参调用，具体原理，我也说过，不甚明白，只管用就对了……
